/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class weld_WeldJNI__ */

#ifndef _Included_weld_WeldJNI__
#define _Included_weld_WeldJNI__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     weld_WeldJNI__
 * Method:    weld_context_new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1context_1new
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_context_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1context_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_context_memory_usage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1context_1memory_1usage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_value_new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1value_1new
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_value_pointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1value_1pointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_get_buffer_pointer
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1get_1buffer_1pointer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_value_run
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1value_1run
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_value_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1value_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_module_compile
 * Signature: (Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1module_1compile
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_module_run
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1module_1run
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_module_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1module_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_error_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1error_1new
  (JNIEnv *, jobject);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_error_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1error_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_error_code
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_weld_WeldJNI_00024_weld_1error_1code
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_error_message
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_weld_WeldJNI_00024_weld_1error_1message
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_conf_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_weld_WeldJNI_00024_weld_1conf_1new
  (JNIEnv *, jobject);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_conf_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1conf_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_conf_get
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_weld_WeldJNI_00024_weld_1conf_1get
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_conf_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1conf_1set
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_load_library
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1load_1library
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     weld_WeldJNI__
 * Method:    weld_set_log_level
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_weld_WeldJNI_00024_weld_1set_1log_1level
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
